### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by Viral-Git** [norahmaria/gi-server#1]
Hai, I want to contribute but I did not understand what should I add at the env 

FRONT_END = Here SHould I add localhost:3000 or the live url??
SECRET = What is the secret token, what should I add here, is it will be any website or any token that  I have to create 
MONGO_DB = Here I need to add Mongoatlas URL
ENVIRONMENT = LIVE | OFFLINE here what I have to 

COuld you please help me?

**Comment by Viral-Git** [comment]
I forked your code and started working on it but the only thing is I stuck with the env I do not understand which should  I use at secret and at the front end and at live or Offline

Please help me

**Comment by norahmaria** [comment]
> I forked your code and started working on it but the only thing is I stuck with the env I do not understand which should I use at secret and at the front end and at live or Offline
> 
> Please help me

Hi! Sorry if the .env.example wasn't clear enough, i've added a bit further instructions on the server and client repositories. But you generally have the right idea, add a .env file in the **src/env** folder and put in your own variables.

**FRONT_END** should be localhost:3000, unless you have a _deployed_ url for your front-end ofc.
**SECRET** should be the secret you want for JWTs, it will be used for authentication between your front-end and server. This should be something random so that it's harder for people to guess.
**MOGNO_DB**, yes add your mongo atlas uri, so that the server knows what database to use.
**ENVIRONMENT** you don't really need this, unless you're deployed - in which case you need to set it to LIVE, this will result in some changes for cookies to allow for secure cross-domain.

Hope that helps 😄
